from linked_class import Set

set1 = Set('abracadabra')
set1.add('l')
set1.remove('a')
set2 = Set('alacazam')
set2.add('s')
set2.remove('l')
print('Set1:', set1)
print('Set2:', set2)
print('Abracadabra equals Alacazam: ', set1.equals(set2))
print('Abracadabra is subset of Alacazam:', set1.is_subset_of(set2))
print('Alacazam is subset of Abracadabra:', set2.is_subset_of(set1))
print('Union:', set1.union(set2))
print('Difference:', set2.difference(set1))
print('Intersection:', set1.intersection(set2))
